Lesson34
slim1979/gse pull request #13
Opened 2018-02-21 18:55 UTC by slim1979

2018-02-23 10:57 UTC, vkurennov requested changes

2018-02-23 10:57 UTC, vkurennov commented on app/controllers/application_controller.rb
> +  rescue_from CanCan::AccessDenied do |exception|
Тут нужно для всех возможных форматов сделать обработку.  Для html - редирект, а для js и json нужно вовзращать 403 ошибку и на клиенте ее обрабатывать

2018-02-23 10:57 UTC, vkurennov commented on app/models/ability.rb
> +    can %i[update destroy], [Question, Answer, Comment], user: user
Тут лучше по user_id сравнивать, чтобы не грузить ассоциацию

2018-02-23 10:57 UTC, vkurennov commented on app/models/ability.rb
> +    can :create, [Question, Answer, Comment, Vote]
У голосования более сложная логика авторизации: нельзя голосовать за свой объект

2018-02-24 21:01 UTC, slim1979 commented on app/models/ability.rb
> +    can :create, [Question, Answer, Comment, Vote]
исправил

2018-02-24 21:57 UTC, slim1979 commented on app/models/ability.rb
> +    can %i[update destroy], [Question, Answer, Comment], user: user
исправил

2018-02-24 21:58 UTC, slim1979 commented on app/controllers/application_controller.rb
> +  rescue_from CanCan::AccessDenied do |exception|
исправил

2018-02-25 09:23 UTC, vkurennov approved these changes

2018-02-25 09:23 UTC, vkurennov commented on app/controllers/application_controller.rb
> +      format.json { head :forbidden, content_type: 'text/html' }
А зачем менять content_type? Тем более, что ответ-то пустой. Пусть и уходит в том же формате, в котром был запрос (js или json)

2018-02-25 09:23 UTC, vkurennov commented on app/controllers/application_controller.rb
> +      format.js   { head :forbidden, content_type: 'text/html' }
И тут тоже не зачем менять формат на html

2018-02-27 18:18 UTC, merged