Lesson38.1
slim1979/gse pull request #19
Opened 2018-04-04 20:18 UTC by slim1979

2018-04-05 12:35 UTC, vkurennov requested changes

2018-04-05 12:35 UTC, vkurennov commented on app/jobs/create_question_job.rb
> +    ThanksMailer.send_thanks(user, question).deliver_now
В  джобах тоже стоить использовать deliver_later  для отправки писем, чтобы задачи паралеллились.

2018-04-05 12:35 UTC, vkurennov commented on app/jobs/create_question_job.rb
> +class CreateQuestionJob < ApplicationJob
В принципе, можно было это и не выносить в отдельный джоб, а отсавить методом в модели, тут ведь всего один запрос, а письмо и так в фоне отправлялось, так что операция не тяжелая

2018-04-05 12:35 UTC, vkurennov commented on app/jobs/daily_digest_job.rb
> +        DailyMailer.digest(email, questions).deliver_now
Тоже замени на deliver_later. Логика тут такая: у тебя есть 25 воркеров, обрабатывающих очередь, ты запускаешь эту задачу, один воркер начинает выполнять ее, запускает цикл и по одному письму отправляет.  Т.е. он и перебор юзеров делаеть и письма формирует и шлет. И пока он не отошлет письмо одному юзеру, не начнет обрабатывать другого. Если же возникнет ошибка на каком-то пиьсме, то все необработанные юзеры так и останутся не обработанными, т.к. задача завершит свою работу.

Если же сделать deliver_later, то один воркер будет перебирать юзеров, а формирование и отправку отправлять в очередь, где эту задачу будут подхватывать оставшиеся 24 воркера. Т.е. письма будут рассылаться паралелльно и если даже какое-то писмьо не отправится, цикл по юзерам все равно будет завершен и для каждого юзера будет поставлена задача отправки письма.

2018-04-05 12:35 UTC, vkurennov commented on app/jobs/new_answer_job.rb
> +        NewAnswerMailer.send_notification(subscription.user, answer.question, answer).deliver_now
Тут тоже deliver_later

2018-04-05 12:35 UTC, vkurennov commented on app/models/question.rb
> +    CreateQuestionJob.perform_later(user, self)
Эти действия должны быть ДО отправки сообщения в кабель, они все-таки важнее.

2018-04-05 12:35 UTC, vkurennov commented on app/models/subscription.rb
> +  validates :user_id, :question_id, presence: true
Поля ассоциаций с 5-х релься не нужно валидировать.

2018-04-05 12:35 UTC, vkurennov commented on app/models/subscription.rb
> +  validates_uniqueness_of :user_id, scope: :question_id
Используй всегда новый формат валидаций: `validates :user_id, uniqueness: { scope: :question_id }`

2018-04-05 12:35 UTC, vkurennov commented on spec/acceptance/subscriptions/subscribe_on_question_spec.rb
> +        expect(current_email.body).to have_content question.title
Тут лучше  проверить ссылку на вопрос и какой-то текст из письма, указывающий на то, что это именно письмо о новом ответе (можно по subject это проверить)

2018-04-05 12:35 UTC, vkurennov commented on spec/jobs/create_question_job_spec.rb
> +RSpec.describe CreateQuestionJob, type: :job do
Где тесты?

2018-04-05 12:35 UTC, vkurennov commented on spec/jobs/daily_digest_job_spec.rb
> +RSpec.describe DailyDigestJob, type: :job do
Где тесты?

2018-04-05 12:35 UTC, vkurennov commented on spec/jobs/new_answer_job_spec.rb
> +RSpec.describe NewAnswerJob, type: :job do
Где тесты?

2018-04-05 12:35 UTC, vkurennov commented on spec/mailers/daily_mailer_spec.rb
> +RSpec.describe DailyMailer, type: :mailer do
А вот на мейлеры тесты можно не писать

2018-04-07 13:49 UTC, slim1979 commented on app/jobs/create_question_job.rb
> +    ThanksMailer.send_thanks(user, question).deliver_now
сделал

2018-04-07 14:08 UTC, slim1979 commented on app/models/question.rb
> +    CreateQuestionJob.perform_later(user, self)
не совсем понимаю, почему они важнее? это же фон... письма могут быть получены и через 5 минут и чуть позже. а через кабель же мы в прямом эфире так сказать вещаем... но если ты считаешь, что это важнее, я, конечно, соглашусь

2018-04-07 14:11 UTC, slim1979 commented on app/jobs/new_answer_job.rb
> +        NewAnswerMailer.send_notification(subscription.user, answer.question, answer).deliver_now
сделал

2018-04-07 14:22 UTC, slim1979 commented on spec/acceptance/subscriptions/subscribe_on_question_spec.rb
> +        expect(current_email.body).to have_content question.title
у меня просто в теле письма нет ничего от ответа

2018-04-07 15:01 UTC, vkurennov approved these changes

2018-04-07 15:01 UTC, vkurennov commented on app/jobs/daily_digest_job.rb
> +        DailyMailer.digest(email, questions).deliver_now
Замени на deliver_later

2018-04-07 22:13 UTC, merged