Lesson26
slim1979/gse pull request #3
Opened 2017-09-20 23:23 UTC by slim1979

2017-09-21 14:13 UTC, vkurennov requested changes

2017-09-21 14:13 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def new
У нас форма ответа должна быть на странице вопроса, поэтому экшена new не должно быть

2017-09-21 14:13 UTC, vkurennov commented on app/controllers/answers_controller.rb
>        render :new
Раз форма ответа на странице вопроса, вот ее и надо рендерить, а не другую страницу

2017-09-21 14:13 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if @answer.user == current_user
* 1. Лучше проверять по user_id, чтобы не грузить ассоциацию из базы, она ведь не нужна.
* 2. Т.к. такая проверка будет встречаться часто, то лучше ее вынести в метод `User#author_of?`

2017-09-21 14:13 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question = current_user.questions.new
в new нет смысла устанавливать связи и ассоциации, это не влияет на форму в большинстве случаев. Все связи на самом деле устанавливаются в create, поэтому тут и Question.new будет работать, ничего не изменится.

2017-09-21 14:13 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if @question.user == current_user
Замени проверку на вызов `User#author_of?`

2017-09-21 14:13 UTC, vkurennov commented on app/views/questions/index.slim
> +            = link_to 'delete question', question_path(question), method: :delete, data: { confirm: 'Вы уверены?' }
Зачем показывать ссылку на удаление всем подряд? Показывай только автору

2017-09-21 14:13 UTC, vkurennov commented on app/views/questions/show.html.slim
> +      .manage = link_to 'Delete answer', answer_path(id: a.id), data: { confirm: 'Are you sure?' }, method: :delete
Зачем показывать ссылку на удаление всем подряд? Показывай только автору

2017-09-21 14:13 UTC, vkurennov commented on spec/acceptance/questions/answer_the_question_spec.rb
> +    expect(page).to have_content question.title
И какой смысл при создании **ответа** проверять наличие **вопроса**?  Проверяй контент ответа на странице после создания

2017-09-21 14:13 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +    expect(page).to have_content 'Your question created successfully!'
Тут нужно проверить заголовок и тело вопроса на странице

2017-09-21 14:13 UTC, vkurennov commented on spec/acceptance/user/browse_through_questions_and_its_answers_spec.rb
> +    expectations
Вот это очень плохая практика - сделать метод, содержащий проверки и назвать его общим именем. Это неудобно смотреть и из названия совершенно не ясно, что там за ожидания. Не говоря уже о том, что такое имя метода подойдет вообще для любой спеки

2017-09-21 14:13 UTC, vkurennov commented on spec/acceptance/user/destroy_answers_spec.rb
> +    click_on 'Delete answer'
Лучше просто не показывать ссылку

2017-09-21 14:13 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +feature 'Create question', %q(
Нужен тест на ошибки валидации - проверить, что система выводит их пользователю.

2017-09-21 14:13 UTC, vkurennov commented on spec/acceptance/questions/answer_the_question_spec.rb
> +feature 'Answer the question', %q(
Нужен тест на ошибки валидации - проверить, что система выводит их пользователю.

2017-09-21 14:13 UTC, vkurennov commented on spec/acceptance/user/destroy_answers_spec.rb
> +    click_on 'Delete answer'
Надо проверить, что ответа больше нет на странице

2017-09-21 14:13 UTC, vkurennov commented on spec/acceptance/user/destroy_answers_spec.rb
> +    click_on 'Delete answer'
Лучше просто не показывать ссылку

2017-09-21 14:13 UTC, vkurennov commented on spec/acceptance/user/destroy_questions_spec.rb
> +    click_on 'delete question'
Надо проверить, что вопроса больше нет на странице

2017-09-21 14:13 UTC, vkurennov commented on spec/acceptance/user/destroy_questions_spec.rb
> +    click_on 'delete question'
Лучше просто не показывать ссылку

2017-09-21 14:13 UTC, vkurennov commented on spec/acceptance/user/destroy_questions_spec.rb
> +    click_on 'delete question'
Лучше просто не показывать ссылку

2017-09-21 14:13 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
И где тесты на destroy? **Любой код, который ты пишешь, должен быть покрыт тестами**

2017-09-21 14:13 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
А в destroy ничего не изменилось? Изменения тоже надо покрывать тестами, ведь теперь твой код работает другим образом.

2017-09-22 12:46 UTC, slim1979 commented on app/controllers/answers_controller.rb
>    def new
удалил

2017-09-22 12:46 UTC, slim1979 commented on app/controllers/answers_controller.rb
>        render :new
исправил

2017-09-22 13:49 UTC, slim1979 commented on app/controllers/questions_controller.rb
> +    @question = current_user.questions.new
вернул, как было)

2017-09-22 13:51 UTC, slim1979 commented on app/controllers/questions_controller.rb
> +    if @question.user == current_user
исправил

2017-09-22 13:54 UTC, slim1979 commented on app/views/questions/index.slim
> +            = link_to 'delete question', question_path(question), method: :delete, data: { confirm: 'Вы уверены?' }
а я же вот специально наверЬху написал, что эта кнопка видима для всех ролей пользователей для того, чтобы продемонстрировать ее поведение для этих самых ролей. и добавил, что она будет скрыта после того, как тесты станут зелеными. зачем я так сделал? затем, что ты сам говорил, что очень легко подделать в dev tools значение кнопки. ну и правда, заходишь, любую кнопку меняешь на нужную и погнал удалять) поэтому я ее оставил именно для того, чтобы убедиться, что такой "взлом" не прокатит. после этого собирался, конечно же, ее скрыть.

2017-09-22 13:55 UTC, slim1979 commented on app/views/questions/show.html.slim
> +      .manage = link_to 'Delete answer', answer_path(id: a.id), data: { confirm: 'Are you sure?' }, method: :delete
та же причина

2017-09-22 13:55 UTC, slim1979 commented on spec/acceptance/questions/answer_the_question_spec.rb
> +feature 'Answer the question', %q(
вот не выводит, как оказалось... буду думать

2017-09-22 14:14 UTC, slim1979 commented on spec/acceptance/questions/answer_the_question_spec.rb
> +    expect(page).to have_content question.title
ну а вдруг с вопросом чего случилось, пока ответ писал))
убрал лишнее, раз ты считаешь, что оно лишнее...

2017-09-22 14:15 UTC, slim1979 commented on spec/acceptance/questions/create_question_spec.rb
> +    expect(page).to have_content 'Your question created successfully!'
добавил

2017-09-22 14:17 UTC, slim1979 commented on spec/acceptance/user/browse_through_questions_and_its_answers_spec.rb
> +    expectations
вернул обратно...
хотелось бОльшей простоты.
посоветуй, как сделать

2017-09-22 14:23 UTC, slim1979 commented on spec/acceptance/user/destroy_answers_spec.rb
> +    click_on 'Delete answer'
проверил

2017-09-23 22:01 UTC, slim1979 commented on app/controllers/answers_controller.rb
> +    if @answer.user == current_user
сделал

2017-09-23 22:11 UTC, slim1979 commented on spec/acceptance/questions/answer_the_question_spec.rb
> +feature 'Answer the question', %q(
исправил, тест добавил

2017-09-23 22:13 UTC, slim1979 commented on spec/acceptance/questions/create_question_spec.rb
> +feature 'Create question', %q(
добавил

2017-09-23 22:17 UTC, slim1979 commented on spec/acceptance/user/destroy_answers_spec.rb
> +    click_on 'Delete answer'
убрал ссылку, изменил тест

2017-09-23 22:18 UTC, slim1979 commented on spec/acceptance/user/destroy_answers_spec.rb
> +    click_on 'Delete answer'
убрал ссылку, изменил тест

2017-09-23 22:24 UTC, slim1979 commented on spec/acceptance/user/destroy_questions_spec.rb
> +    click_on 'delete question'
добавил

2017-09-23 22:24 UTC, slim1979 commented on spec/acceptance/user/destroy_questions_spec.rb
> +    click_on 'delete question'
исправил

2017-09-23 22:24 UTC, slim1979 commented on spec/acceptance/user/destroy_questions_spec.rb
> +    click_on 'delete question'
исправил

2017-09-23 22:24 UTC, slim1979 commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
пардоньте

2017-09-23 23:39 UTC, slim1979 commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
добавил проверку на попытку удаления вопроса другим автором

2017-09-24 11:02 UTC, vkurennov requested changes

2017-09-24 11:02 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      render 'questions/show', resource: @answer
Здесь нет смысла передавать resource, он не попадет в вид. Зато в виде будет доступна переменная `@answer`

2017-09-24 11:02 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @question
Редиректы одинаковые, только сообщения разные. Зачем тогда редирект в условие помещать?

2017-09-24 11:02 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +      redirect_to questions_path
Опять редирект одинаковый, вынеси из условия

2017-09-24 11:02 UTC, vkurennov commented on app/views/questions/show.html.slim
> +      -if answer.valid?
Лучше вызывай `persisted?`, этот метод проверяет, сохранен ли объект в базе. При вызове `valid?` ты каждый раз заново прогоняешь все валидации, а этого делать не нужно

2017-09-24 11:02 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    = render 'common/errors', resource: @answer
Вот видишь, не нужно в контроллере передавать `resource,` все равно здесь явно приходится передавать `@answer`

2017-09-24 11:02 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'Answer by Author' do
Ну так раз есть контекст для автора, должен быть контекст и для не-автора. вообще, если у тебя в коде есть ветвление, то нужно писать тесты для всех возможных вариантов

2017-09-25 11:41 UTC, vkurennov approved these changes

2017-09-26 11:44 UTC, merged