Lesson28
slim1979/gse pull request #6
Opened 2017-10-02 14:17 UTC by slim1979

2017-10-02 14:42 UTC, vkurennov requested changes

2017-10-02 14:42 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def best_answer_assign
Это действие над **ответом**, поэтому правильнее сделать экшн в контроллере ответов

2017-10-02 14:42 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question.turn_off_old_best_answer if @question.best_answer
1. Тут у тебя слишком много логики, она все должна быть в модели, а не в контроллере
2. Это действия над ответом, поэтому и методы должны быть в модели ответа
3. Раз у тебя несколько апдейтов, то все их нужно обернуть в транзакцию, чтобы изменения были атомарными

2017-10-02 14:42 UTC, vkurennov commented on app/models/question.rb
> +    answers.find(best_answer).update(best_answer: false) if best_answer
Ты как-то странно работаешь с ассоциациями. Зачем делать find, если при правильно прописанной ассоциации, все будет автоматом происходить? Но вообще-то тут надо решать не через ассоциации, иначе нарушается связь между родителем и потомком. Лучше сделать логическое поле в таблице answers

2017-10-02 14:42 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +      =form_tag best_answer_assign_question_path(answer.question), method: :patch, remote: true do
Зачем тут форма? Достаточно ссылки с методом patch

2017-10-02 14:42 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +        = hidden_field_tag :best_answer, answer.id
Мы такое на базовом курсе могли использовать, но на продвинутом это очень некрасиво. У тебя есть параметры запроса, а еще лучше - указывать прямо в url, особенно, если делать запрос к контроллеру ответов

2017-10-02 14:42 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def update
Где проверка на автора, которая долна быть по условию?

2017-10-02 14:42 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question.update(question_params)
Где проверка на автора?

2017-10-02 14:42 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def best_answer_assign
и где проверка на автора?

2017-10-02 14:42 UTC, vkurennov commented on app/views/answers/update.js.erb
> +    $(".body_of_<%= @answer.id %>").html('<%= @answer.body %>').show();
А не проще весь div  c ответом обновить?

2017-10-02 14:42 UTC, vkurennov commented on spec/acceptance/answers/best_answer_spec.rb
> +  scenario 'Authenticated author of question', js: true do
Это все? А то, что если был другой лучши ответ, то он теряет эту отметку? А то, что лучший ответ именно первый?

2017-10-02 14:42 UTC, vkurennov commented on spec/acceptance/answers/best_answer_spec.rb
> +    expect(page).to have_button 'Best answer'
И? Как работает эта кнопка? Можно просто сделать кнопку и никакой код больше не писать, тест пройдет. Это будет считаться, что фича реализована? Помни, что acceptance-тесты - это **приемочные**  тесты, т.е. их цель - доказать, что фича работает так, как должна.

2017-10-02 14:42 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'Answer by someone else'
Где тесты-то?

2017-10-02 14:42 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: answer }, format: :js }.to_not change(question.answers, :count)
Тут просто Answer должно быть в change, важно проверить, что вообще никакие ответы не были удалены

2017-10-02 14:42 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: answer }, format: :js }.to_not change(question.answers, :count)
И тут просто Answer  в change

2017-10-02 14:42 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'valid attributes' do
Нужны контексты для автора и для не-автора

2017-10-03 18:44 UTC, slim1979 commented on app/controllers/questions_controller.rb
> +    @question.update(question_params)
добавил

2017-10-03 18:44 UTC, slim1979 commented on app/controllers/questions_controller.rb
> +  def best_answer_assign
перенес

2017-10-03 19:02 UTC, slim1979 commented on app/controllers/questions_controller.rb
> +  def best_answer_assign
добавил

2017-10-03 19:02 UTC, slim1979 commented on app/controllers/questions_controller.rb
> +    @question.turn_off_old_best_answer if @question.best_answer
пересобрал в другом месте

2017-10-03 19:02 UTC, slim1979 commented on app/models/question.rb
> +    answers.find(best_answer).update(best_answer: false) if best_answer
объяснил позицию на ИЗ, переделал

2017-10-03 19:03 UTC, slim1979 commented on app/views/answers/_answer.html.slim
> +      =form_tag best_answer_assign_question_path(answer.question), method: :patch, remote: true do
переделал

2017-10-03 19:03 UTC, slim1979 commented on app/views/answers/_answer.html.slim
> +        = hidden_field_tag :best_answer, answer.id
согласился, переделал

2017-10-03 19:03 UTC, slim1979 commented on app/controllers/answers_controller.rb
> +  def update
добавлена

2017-10-03 19:03 UTC, slim1979 commented on app/views/answers/update.js.erb
> +    $(".body_of_<%= @answer.id %>").html('<%= @answer.body %>').show();
нет, там строка таблицы

2017-10-03 19:04 UTC, slim1979 commented on spec/acceptance/answers/best_answer_spec.rb
> +  scenario 'Authenticated author of question', js: true do
сделал по твоим советам. спасибо, кстати)

2017-10-03 19:05 UTC, slim1979 commented on spec/controllers/answers_controller_spec.rb
> +    context 'Answer by someone else'
добавил. странно то, что guard мне не выдавал сообщений про pending. поэтому и забыл про него. но от зоркого глаза сенсея не скрыться)

2017-10-03 19:07 UTC, slim1979 commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: answer }, format: :js }.to_not change(question.answers, :count)
вернул, как было

2017-10-03 19:07 UTC, slim1979 commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: answer }, format: :js }.to_not change(question.answers, :count)
вернул, как было

2017-10-03 19:08 UTC, slim1979 commented on spec/controllers/questions_controller_spec.rb
>      context 'valid attributes' do
добавил

2017-10-04 12:47 UTC, vkurennov approved these changes

2017-10-04 12:47 UTC, vkurennov commented on spec/acceptance/answers/best_answer_spec.rb
> +        expect(page).to have_xpath('//img[@src="/assets/best-272f2f9e50eba3e954cc7a3de060a1d47823677f3589b08e0aa270c327d02782.png"]')
Вот это очень "хрупко", хеш картинки изменится и тест полетит. Тут лучше тогда не на картинку, а на класс завязаться, а картинку через css подставлять

2017-10-04 12:47 UTC, vkurennov commented on spec/acceptance/answers/best_answer_spec.rb
> +        expect(page).to have_xpath('//img[@src="/assets/best-272f2f9e50eba3e954cc7a3de060a1d47823677f3589b08e0aa270c327d02782.png"]')
И тут лучше использовать класс

2017-10-06 20:10 UTC, merged