Lesson29
slim1979/gse pull request #7
Opened 2017-10-09 15:15 UTC by slim1979

2017-10-09 18:51 UTC, vkurennov requested changes

2017-10-09 18:51 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def attach
Не нужно делать кастомный экшн, да еще и с неочевидным названием. attach  - это прекрипить, а у тебя он удаляет аттачмент. на самом деле, если операции укладываются в CRUD, лучше всего сделать отдельный ресурс, пусть и с одним экшеном

2017-10-09 18:51 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def attach
Дублирование не смущает?

2017-10-09 18:51 UTC, vkurennov commented on spec/acceptance/answers/add_files_to_answer_spec.rb
> +  scenario 'User adds files when asked question', js: true do
Нужно проверить добавление нескольких файлов

2017-10-10 20:14 UTC, slim1979 commented on spec/acceptance/answers/add_files_to_answer_spec.rb
> +  scenario 'User adds files when asked question', js: true do
добавил. на другой ветке было, забыл слить

2017-10-11 10:36 UTC, vkurennov approved these changes

2017-10-11 10:36 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  before_action :set_answer, except: %i[create attach]
У тебя нет больше экшена attach

2017-10-11 10:36 UTC, vkurennov commented on app/controllers/attaches_controller.rb
> +class AttachesController < ApplicationController
ну вот, теперь все просто и понятно

2017-10-11 10:36 UTC, vkurennov commented on spec/controllers/attaches_controller_spec.rb
> +    context 'question attach' do
А зачем ты делаешь на разных объектах? Это не важно, у тебя же вообще не зависит контроллер от объекта, с которым связан аттач.

2017-10-18 15:44 UTC, merged