Lesson30
slim1979/gse pull request #8
Opened 2017-11-28 20:15 UTC by slim1979

2017-11-29 08:24 UTC, vkurennov requested changes

2017-11-29 08:24 UTC, vkurennov commented on Gemfile
> +gem 'skim'
Зачем оба гема? Используй какой-то один шаблонизатор

2017-11-29 08:24 UTC, vkurennov commented on app/assets/javascripts/answers.js.coffee
> +        errors = ('<div id="editing_errors_'+response.resource.id+'" class="alert fade in alert-danger"')
Здесь тоже следует применить js-шаблонизатор.

2017-11-29 08:24 UTC, vkurennov commented on app/assets/javascripts/answers.js.coffee
> +        link += ('<li id="file_'+value.attach.id+'">')
И здесь тоже нужен js-шаблонизатор, в skim, кстати, можно использовать jquery и сделать итератор по аттачемнтам.

2017-11-29 08:24 UTC, vkurennov commented on app/assets/javascripts/answers.js.coffee
> +      errors = ('<div class="answer_errors alert fade in alert-danger"')
Вынеси в js-шаблон. Причем, шаблон желательно универсальный для ошибко вопросв и ответов

2017-11-29 08:24 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +        format.html { render partial: 'answers/answers', layouts: false }
Зачем поддерживать и html и json? Это нужно делать, когда такое требование есть в ТЗ. Но если этого нет, оставь только один возможный вариант.

2017-11-29 08:24 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      format.json { render json: @answer.as_json } unless @answer.errors.present?
Если формат только один, то не нужен блок respond_to

2017-11-29 08:24 UTC, vkurennov commented on app/controllers/attaches_controller.rb
> +    respond_to { |format| format.json { render json: @attach } }
Опять же не нежен respond_to, если поддерживается только json. Просто пиши `render json: @attach`

2017-11-29 08:24 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +  def any
Очень плохое название экшена, потому что вообще не ясно что он делает. Если создает голос, назови create, если он делает все, значит, плохая архитектура и надо разделить на несколько действий. Помни о принципе единой ответственности.

2017-11-29 08:24 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +    subject_type = params[:subject_type]
Сделай этот контроллер вложенным в вопросы/ответы, тогде не нужно будет передавать тип и id родителя, т.к. они будут содержаться в url. И можено будет [динамически загрузить](https://stackoverflow.com/questions/26318815/polymorphic-controller-and-calling-object) этот объект на основе этих данных

2017-11-29 08:24 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +  def any
Кроме того, контроллер получается перегружен бизнес-логикой. Если нам понадобится сделать API-контроллер для голосования, то придется весь код дублировать и если что-то изменится, то менять придется уже в нескольких местах. Контролелры не должны содержать логики, кроме логики отображения (что рендерить или куда редиректить).

Лучше всего, сделать тут экшн create, а логику по созданию/апдейту перенести в модель. Т.е. контроллер будет просто вызывать у вопроса/ответа метод голосования, передавая туда юзера, а метод уже будет сам решать, что делать - создавать голос или апдейтить.

2017-11-29 08:24 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +    respond_to { |format| format.json { render partial: 'votes/votes' } }
Не нужен respond_to

2017-11-29 08:24 UTC, vkurennov commented on app/models/vote.rb
> +  validates :user, uniqueness: { scope: :subject_id }
Почему уникальность только по id? Если юзер проголосвал за вопрос с  id 1, он что, не может проголосовать за ответ с таким же id? Это ведь совершенно другой объект.

2017-11-29 08:24 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +        .vote = link_to 'like', any_votes_path( subject_type: Answer, subject_id: answer, votes_value: 1 ), remote: true, method: :patch if current_user
Чтобы не передавать subject_type и subject_id, используй вложенные роуты.

2017-11-29 08:24 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +        .vote = link_to 'dislike', any_votes_path( subject_type: Answer, subject_id: answer, votes_value: -1 ), remote: true, method: :patch if current_user
Что-то я нигде не нашел ссылки голосования за вопрос.

2017-11-30 13:49 UTC, slim1979 commented on Gemfile
> +gem 'skim'
убрал

2017-11-30 15:41 UTC, slim1979 commented on app/assets/javascripts/answers.js.coffee
> +        errors = ('<div id="editing_errors_'+response.resource.id+'" class="alert fade in alert-danger"')
заменил)

2017-11-30 15:57 UTC, slim1979 commented on app/assets/javascripts/answers.js.coffee
> +        link += ('<li id="file_'+value.attach.id+'">')
сделал

2017-11-30 16:06 UTC, slim1979 commented on app/controllers/answers_controller.rb
> +        format.html { render partial: 'answers/answers', layouts: false }
исправил

2017-11-30 16:06 UTC, slim1979 commented on app/controllers/answers_controller.rb
> +      format.json { render json: @answer.as_json } unless @answer.errors.present?
исправил

2017-11-30 16:07 UTC, slim1979 commented on app/controllers/attaches_controller.rb
> +    respond_to { |format| format.json { render json: @attach } }
ну не везде еще понимаю, что лишнее, что нет...
испрвил

2017-12-02 01:24 UTC, slim1979 commented on app/views/answers/_answer.html.slim
> +        .vote = link_to 'dislike', any_votes_path( subject_type: Answer, subject_id: answer, votes_value: -1 ), remote: true, method: :patch if current_user
добавил

2017-12-02 01:24 UTC, slim1979 commented on app/views/answers/_answer.html.slim
> +        .vote = link_to 'like', any_votes_path( subject_type: Answer, subject_id: answer, votes_value: 1 ), remote: true, method: :patch if current_user
использовал

2017-12-02 01:56 UTC, slim1979 commented on app/models/vote.rb
> +  validates :user, uniqueness: { scope: :subject_id }
просто изначально делал для ответов, поэтому так. исправил.

2017-12-02 01:57 UTC, slim1979 commented on app/controllers/votes_controller.rb
> +    respond_to { |format| format.json { render partial: 'votes/votes' } }
исправил. вообще всё, причём)

2017-12-02 01:57 UTC, slim1979 commented on app/controllers/votes_controller.rb
> +    subject_type = params[:subject_type]
сделал

2017-12-02 01:58 UTC, slim1979 commented on app/controllers/votes_controller.rb
> +  def any
согласен, исправил

2017-12-02 01:58 UTC, slim1979 commented on app/controllers/attaches_controller.rb
> +    respond_to { |format| format.json { render json: @attach } }
принял

2017-12-02 01:58 UTC, slim1979 commented on app/controllers/answers_controller.rb
> +      format.json { render json: @answer.as_json } unless @answer.errors.present?
приянл

2017-12-02 01:58 UTC, slim1979 commented on app/controllers/answers_controller.rb
> +        format.html { render partial: 'answers/answers', layouts: false }
убрал лишнее

2017-12-02 01:59 UTC, slim1979 commented on app/assets/javascripts/answers.js.coffee
> +      errors = ('<div class="answer_errors alert fade in alert-danger"')
вынес

2017-12-02 01:59 UTC, slim1979 commented on app/assets/javascripts/answers.js.coffee
> +        link += ('<li id="file_'+value.attach.id+'">')
сделал

2017-12-02 01:59 UTC, slim1979 commented on app/assets/javascripts/answers.js.coffee
> +        errors = ('<div id="editing_errors_'+response.resource.id+'" class="alert fade in alert-danger"')
применил

2017-12-02 02:00 UTC, slim1979 commented on Gemfile
> +gem 'skim'
убрал усы

2017-12-11 07:33 UTC, vkurennov approved these changes

2017-12-20 12:36 UTC, merged