Lesson31
slim1979/gse pull request #9
Opened 2017-12-20 12:37 UTC by slim1979

2017-12-23 06:09 UTC, vkurennov requested changes

2017-12-23 06:09 UTC, vkurennov commented on .idea/.generators
> +<?xml version="1.0" encoding="UTF-8"?>
Папку .idea надо вообще в .gitignore добавить. Это локальные настройки редактора, они не должны в репозиторий попадать

2017-12-23 06:09 UTC, vkurennov commented on app/assets/javascripts/answers.coffee
> +        answer = response.publish.answer
а зачем разбирать json по переменным? передай нужный json в JST и там уже бери нужные значения

2017-12-23 06:09 UTC, vkurennov commented on app/channels/answers_channel.rb
> +    stream_from 'answers'
У тебя получается общий стрим для всех ответов, т.е. юзер будет получать ответы вообще для всех вопросов в системе, вне зависимости от того, смотрит он этот вопрос или нет. Нужно в имя стрима включать question_id, для этого его надо передавать в параметрах при подключении

2017-12-23 06:09 UTC, vkurennov commented on app/channels/comments_channel.rb
> +  end
Тут то же самое - общий канал для вообще всех комментариев, которые создаются в системе, это будет создавать лишнюю нагрузку на браузер.

2017-12-26 18:04 UTC, slim1979 commented on .idea/.generators
> +<?xml version="1.0" encoding="UTF-8"?>
добавил

2017-12-26 18:05 UTC, slim1979 commented on app/assets/javascripts/answers.coffee
> +        answer = response.publish.answer
упростил

2017-12-26 18:11 UTC, slim1979 commented on app/channels/answers_channel.rb
> +    stream_from 'answers'
переделал

2017-12-26 19:04 UTC, slim1979 commented on app/channels/comments_channel.rb
> +  end
изменил. так же изменил подключение к потоку вопросов.

2017-12-27 00:46 UTC, merged